const state={breakers:[],selected:null,editing:false};
const $=s=>document.querySelector(s);
const fmt=n=>Number(n||0).toLocaleString();
const pct=n=>`${(Number(n||0)*100).toFixed(1)}%`;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`HTTP ${res.status}`);return body}
function notice(message){const node=$('#notice');node.textContent=message;node.classList.remove('hidden');setTimeout(()=>node.classList.add('hidden'),3500)}
function metric(label,value){return `<div class="card"><span>${label}</span><strong>${value}</strong></div>`}
function badge(value){return `<span class="badge ${esc(value)}">${esc(value).replace('_',' ')}</span>`}
async function loadGlobal(){const data=await api('/api/metrics');$('#global').innerHTML=[metric('总请求',fmt(data.total)),metric('成功',fmt(data.succeeded)),metric('失败 / 超时',fmt(data.failed+data.timeouts)),metric('拒绝',fmt(data.rejected)),metric('整体错误率',pct(data.error_rate))].join('')}
async function loadBreakers(){const list=await api('/api/breakers');state.breakers=list;if(!state.selected&&list.length)state.selected=list[0].resource;if(state.selected&&!list.some(x=>x.resource===state.selected))state.selected=list[0]?.resource||null;$('#breaker-list').innerHTML=list.map(item=>`<div class="breaker-item ${item.resource===state.selected?'selected':''}" data-name="${esc(item.resource)}"><div class="breaker-row"><strong>${esc(item.resource)}</strong>${badge(item.state)}</div><div class="breaker-meta"><span>错误 ${pct(item.error_rate)}</span><span>请求 ${fmt(item.total)}</span><span>拒绝 ${fmt(item.rejected)}</span></div></div>`).join('');document.querySelectorAll('.breaker-item').forEach(node=>node.onclick=()=>{state.selected=node.dataset.name;loadAll()});const select=$('#sim-resource');const current=select.value;select.innerHTML=list.map(x=>`<option value="${esc(x.resource)}">${esc(x.resource)}</option>`).join('');if(list.some(x=>x.resource===current))select.value=current}
function chart(windowData){const buckets=windowData.buckets||[];if(!buckets.length)return '<div class="empty" style="min-height:150px">窗口暂无数据</div>';const max=Math.max(1,...buckets.map(b=>b.succeeded+b.failed+b.timeouts+b.rejected_c+b.rejected_b));return `<div class="chart">${buckets.map(b=>{const unit=v=>Math.max(v?3:0,v/max*100);return `<div class="bar-wrap" title="${new Date(b.start).toLocaleTimeString()} 成功:${b.succeeded} 失败:${b.failed} 超时:${b.timeouts} 拒绝:${b.rejected_c+b.rejected_b}"><div class="bar rejected" style="height:${unit(b.rejected_c+b.rejected_b)}%"></div><div class="bar timeout" style="height:${unit(b.timeouts)}%"></div><div class="bar failed" style="height:${unit(b.failed)}%"></div><div class="bar success" style="height:${unit(b.succeeded)}%"></div></div>`}).join('')}</div>`}
function configForm(c){const fields=[['错误率阈值','error_threshold',c.error_threshold,'0.01'],['最小请求数','min_requests',c.min_requests,'1'],['窗口桶数','window_size',c.window_size,'1'],['桶时长 ms','bucket_duration_ms',c.bucket_duration_ms,'1'],['冷却时间 ms','sleep_window_ms',c.sleep_window_ms,'1'],['探测并发','probe_count',c.probe_count,'1'],['成功阈值','success_threshold',c.success_threshold,'1'],['最大并发','max_concurrency',c.max_concurrency,'1'],['调用超时 ms','call_timeout_ms',c.call_timeout_ms,'1']];return `<div class="config-grid">${fields.map(f=>`<label>${f[0]}<input data-key="${f[1]}" type="number" step="${f[3]}" value="${f[2]}"></label>`).join('')}</div><div class="config-actions"><button id="save-config">保存配置</button><button id="reset">重置指标</button><select id="force-state"><option value="closed">closed</option><option value="open">open</option><option value="half_open">half_open</option></select><button id="set-state">切换状态</button><button id="probe">手动探测</button></div>`}
async function loadDetail(){if(state.editing)return;if(!state.selected){$('#detail').innerHTML='<div class="empty">暂无熔断器</div>';return}const [d,events]=await Promise.all([api(`/api/breakers/${encodeURIComponent(state.selected)}`),api(`/api/events?resource=${encodeURIComponent(state.selected)}&limit=50`)]);const m=d.metrics;$('#detail').innerHTML=`<div class="detail-head"><div><h2>${esc(d.resource)}</h2><p class="muted">最近变更 ${new Date(d.state_changed_at).toLocaleString()}</p></div>${badge(d.state)}</div><div class="cards detail-grid">${metric('累计请求',fmt(m.total_requests))}${metric('成功',fmt(m.succeeded))}${metric('失败',fmt(m.failed))}${metric('超时',fmt(m.timeouts))}${metric('P95 延迟',`${fmt(m.p95_latency_ms)} ms`)}${metric('熔断拒绝',fmt(m.rejected_by_breaker))}${metric('并发拒绝',fmt(m.rejected_by_concurrency))}${metric('探测成功',fmt(m.probe_success))}${metric('探测失败',fmt(m.probe_failed))}${metric('当前并发',fmt(m.in_flight))}</div><div class="section"><h3>滑动窗口</h3>${chart(d.window)}</div><div class="section"><h3>状态与事件</h3><div class="timeline">${events.length?events.map(e=>`<div class="event"><strong>${esc(e.type)}</strong> ${e.data?.from?`${esc(e.data.from)} → ${esc(e.data.to)}`:''}<div>${esc(e.data?.reason||'')}</div><small>${new Date(e.time).toLocaleString()}</small></div>`).join(''):'<div class="muted">暂无事件</div>'}</div></div><div class="section"><h3>动态配置</h3>${configForm(d.config)}</div>`;bindDetailActions()}
function bindDetailActions(){$('#detail').onfocusin=()=>state.editing=true;$('#detail').onfocusout=()=>state.editing=false;$('#save-config').onclick=async()=>{const body={};document.querySelectorAll('[data-key]').forEach(input=>body[input.dataset.key]=Number(input.value));await api(`/api/breakers/${encodeURIComponent(state.selected)}/config`,{method:'PUT',body:JSON.stringify(body)});await loadAll()};$('#reset').onclick=()=>action('reset');$('#probe').onclick=()=>action('probe');$('#set-state').onclick=async()=>{await api(`/api/breakers/${encodeURIComponent(state.selected)}/state`,{method:'POST',body:JSON.stringify({state:$('#force-state').value})});await loadAll()}}
async function action(name){await api(`/api/breakers/${encodeURIComponent(state.selected)}/${name}`,{method:'POST'});await loadAll()}
async function simulate(){const body={resource:$('#sim-resource').value,fail_rate:Number($('#sim-rate').value)/100,latency_ms:Number($('#sim-latency').value),seconds:Number($('#sim-seconds').value)};await api('/api/demo/simulate',{method:'POST',body:JSON.stringify(body)});await loadSimulation()}
async function loadSimulation(){const list=await api('/api/demo/status');$('#sim-status').textContent=list.length?list.map(x=>`${x.resource}: 失败 ${pct(x.fail_rate)}，至 ${new Date(x.expires_at).toLocaleTimeString()}`).join('；'):'当前无故障注入'}
async function loadAll(){try{await Promise.all([loadGlobal(),loadBreakers(),loadSimulation()]);await loadDetail()}catch(err){notice(err.message)}}
$('#refresh').onclick=loadAll;$('#simulate').onclick=()=>simulate().catch(e=>notice(e.message));$('#stop-sim').onclick=async()=>{try{await api('/api/demo/stop',{method:'POST'});await loadSimulation()}catch(e){notice(e.message)}};$('#sim-rate').oninput=e=>$('#rate-label').textContent=`${e.target.value}%`;loadAll();setInterval(loadAll,2000);
